### ISSUE TITLE
Resume templates

### ISSUE THREAD

**Issue by ahmedelsensar11** [medhatdawoud/AMA#15]
Can you recommend me an inspired resume templates as a jonior developer to prepare my CV ?

**Comment by AhmedMuhammedElsaid** [comment]
Hey Dude, 
Take this template it's a professional one and i got many offers when I used it

https://docs.google.com/document/d/1hD1LZWtVI3CBqgmw4AferZmsz_Y1DsWAdcOJGNVgJm4/edit

**Comment by AhmedMuhammedElsaid** [comment]
Hello Dude, 
Use this professional template, I got many opportunities when I used it 

Link:
https://docs.google.com/document/d/1hD1LZWtVI3CBqgmw4AferZmsz_Y1DsWAdcOJGNVgJm4/edit?usp=sharing

**Comment by medhatdawoud** [comment]
Hi Ahmed,

There are tons of the templates online, what I can recommend to you is to create single page as @AhmedMuhammedElsaid suggested, don't put a lot of details because more details should come into your linkedin account, be concise and always adjust your resume to the job you are applying for, so if you are applying for a backend ASP.net developer, emphasising that you know python wouldn't help, be smart in putting only what would push your resume up between other candidates, I wish you all the luck 🙂

Cheers,
Medhat
