### ISSUE TITLE
I hate TypeScript 😡

### ISSUE THREAD

**Issue by lenaggar** [medhatdawoud/AMA#18]
Hi 👋
I am [Naggar](https://twitter.com/lenaggar) 💪 a frontend developer, and I have a problem getting along with TypeScript.

During almost 4 years of my experience I tried it a lot and I appreciate the advantages it offers (type safety, better refactoring, IDE itellisense, bla bla...), I really do. But for me it just doesn't feel right, it makes development of new features harder and the code becomes ugly and verbose 😷 **especially if used with _React_**
So, I also tried Elm 😍 and ReasonML 😍 and they both are statically typed languages that compile to JS but unlike TS, they are much better for me as a developer, development in Elm is a breeze ❤️

The thing is, I feel like an outsider when in the community with everyone I know hyping along with TS and I am not 🤷‍♂

**Comment by medhatdawoud** [comment]
Hi Naggar, 

Thanks for your question which is very common for a lot of ppl, first of all, I used to feel the same so you are not alone, the thing is that TypeScript doesn't require any learning curve if you are good enough in JavaScript then you can start writing TypeScript easily from now, I'm with you that it might sometime make the code more verbose but it has its benefit, and regarding the other options you mentioned I didn't like that much since they have kind of a different syntax than JS that I love to write.

Currently, I'm working full time on a project with the exact same stack React with TypeScript, and my life couldn't be easier or happier, it can be a pain in the neck while setting up everything in the beginning but later you will feel way better, and it's not about the hype, it's more about the community support and the ease of learning and building with it.

If you would like to pair with me in that try my open-source [lib repo](https://github.com/medhatdawoud/react-change-highlight) it's in React with TypeScript, try it and play around and you might create a new feature that could be merged as well 😉 also you can hear more in the [video](https://www.youtube.com/watch?v=plzLYe3b0D8) I made before with some friends about it on my channel

I hope that helps, Medhat.
