### ISSUE TITLE
learning angular before react 

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [medhatdawoud/AMA#3]
Thanks @medhatdawoud for your time.

And I'm happy for being the first one posting here.

I think knowing angular will help understanding react !!

like using typescript, rxjs ..

agree with me?

**Comment by medhatdawoud** [comment]
Short answer: Nope

Long answer: In my opinion, start with whatever you start with, for example, I've started with backbonejs long time ago then turned to angularjs then I got a project in angular 2 since it was RC4 not even released but the client asked us to use it back then, that's why we started learning it a bit early, then another project was requiring reactjs, that's why I've switched to reactjs with Javascript.

What I want to say is that don't learn something for the seak of having it in your arsenal, learn it to use it or make POCs, learning angular before react is not necessary, the only thing that might make you feel better is if you are going to use TypeScript with react, which you are enforced to use with angular, so it will help in enriching your TypeScript knowledge of course.

Hope that helps, Cheers.
