### ISSUE TITLE
Wasted Renders in Redux App using Container Pattern

### ISSUE THREAD

**Issue by Migggz** [medhatdawoud/AMA#38]
Hi Medhat,
Hope you are doing well.

### Brief
I'm usually using **Container Pattern** in large scale react applications alongside **Redux**
> Container components are responsible for data fetching, connecting to redux state and call actions callbacks from presentational component.

### Conditions
If there a container component (TodoWrapper) returns a map function that loops over Todos in redux state. and passing an action as a callback to each one of Todos. this action toggles whether the Todo done or not.

Each one of Todos have a checkbox (or anything that triggers the callback which is changes the redux state), this checkbox indicates to the state of that todo which is done or not.

### Issue
I've noticed that the container itself rerenders while toggling single Todo state.
My assumption is the single todo itself rerenders, not the container and the all children.

### Discussion
**Container Pattern** is really good for separation of concerns, but it costs a lot **wasted renders**. so, is it really good pattern? or there is another pattern for handling this type of issues?

**Comment by medhatdawoud** [comment]
Hi Maged,

That's a very good question, actually using container component is quite common, the problem is usually about managing data either using redux or the local state or the implementation, I'm suspicious about one thing but need to see code, can you send me her the container component you are using so I can give you proper help.

Thanks,
Medhat
