### ISSUE TITLE
Career path directions

### ISSUE THREAD

**Issue by abdeldjalilhachimi** [medhatdawoud/AMA#5]

**Comment by medhatdawoud** [comment]
Just cleaned up the title 

> Hello there! I hope you are doing well, I would like to ask you about How can I stay motivated when I feel down with job refused, and What do you think if you can make a CV review for Us

**Comment by medhatdawoud** [comment]
Hi Abdeldjalil,

that's a great question, regarding feeling down of being rejected, I think that's normal as everyone wants to feel accepted but in our field specially if you are in the beginning(in the first 5 years usually) it's totally fine to get more rejections than acceptance, and I would like to advice to get this as a motivation to enhance yourself, at some point you will reject offers not vice versa.

I'd give you a very important trick I used to do until I made up my Resume, first of all make your linkedin profile updated because this is how employers can see more about you, make your Resume very short and to the point, most of the companies don't care for example what is your hoppy, to build the CV of Resume with the most important parts, just search for like 10 jobs you would like to apply for and read the description and requirements very well, then figure out what are the gaps you have in your CV to fulfil the requirements, then work on yourself to learn it and add it to your CV and so on for all the missing parts, in the end you will build a great CV and might be sorted out on top always.

Just let me know after you apply this advice if it was helpful for you.

Cheers,
Medhat
