### ISSUE TITLE
Interview preparation 

### ISSUE THREAD

**Issue by egenedy97** [medhatdawoud/AMA#8]
How can I  can prepare for an interview in frontend Development  aboard ? 
 @medhatdawoud

**Comment by medhatdawoud** [comment]
Hi Eslam,

let me know what do you miss and what you know so I can build up on it, I was thinking about making a series of videos about interviews in general, but since you opened the topic can you help me with that, just give me some ideas of what you know and what you need to know.

Cheers,
Medhat

**Comment by medhatdawoud** [comment]
Hi Eslam,

I'll close this ticket since I got no reaction from you for a while, so I'll assume that this was enough for answering this question, if you have any further questions always write it here as well.

Regards,
Medhat
